#
#  Copyright 2025 by C Change Labs Inc. www.c-change-labs.com
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
from typing import Any

from openepd.model.common import Amount

# Do not edit this file.
# It is generated with tools/openepd/codegen/generate_category_tree.py, or `make codegen-category-tree`


def get_category_definitions() -> tuple[dict[str, Any], ...]:
    """
    Return the tuple of category definitions used to build the category tree.

    :return: Tuple of dictionaries, each representing a category definition.
    """

    # The returned value is not a constant and is intended for temporary use only.
    # For persistent access to the category tree, use the immutable CATEGORY_TREE mapping instead.
    return (
        {
            "unique_name": "ConstructionMaterials",
            "display_name": "Product Categories",
            "hierarchical_name": "",
            "alt_names": ["Construction Materials"],
            "description": "Root node for all materials",
            "parent": None,
        },
        {
            "unique_name": "Steel",
            "display_name": "Steel",
            "hierarchical_name": "Steel",
            "description": "Broad category for construction materials made from steel and its alloys",
            "masterformat": "05 00 00 Metals",
            "declared_unit": Amount(qty=1.0, unit="t"),
            "parent": "ConstructionMaterials",
        },
        {
            "unique_name": "StructuralSteel",
            "display_name": "Structural Steel",
            "hierarchical_name": "Steel >> StructuralSteel",
            "description": "Hot rolled steel shapes, Hollow Sections, pipes, and similar hot-worked structural steels",
            "masterformat": "05 12 00 Structural Steel Framing",
            "declared_unit": Amount(qty=1.0, unit="t"),
            "parent": "Steel",
        },
        {
            "unique_name": "HollowSections",
            "display_name": "Hollow Sections",
            "hierarchical_name": "Steel >> StructuralSteel >> HollowSections",
            "description": "ollow cross section steel shape, typically referred to as hollow structural section (HSS)",
            "masterformat": "05 12 00 Structural Steel Framing",
            "declared_unit": Amount(qty=1.0, unit="t"),
            "parent": "StructuralSteel",
        },
        {
            "unique_name": "PlateSteel",
            "display_name": "Plate Steel",
            "hierarchical_name": "Steel >> StructuralSteel >> PlateSteel",
            "short_name": "Plate",
            "description": "Flat hot-rolled steel, typically thicker than 'sheet', made by compressing multiple steel layers together into one",
            "masterformat": "05 12 00 STRUCTURAL STEEL FRAMING",
            "declared_unit": Amount(qty=1.0, unit="t"),
            "parent": "StructuralSteel",
        },
    )
