#
#  Copyright 2024 by C Change Labs Inc. www.c-change-labs.com
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  This software was developed with support from the Skanska USA,
#  Charles Pankow Foundation, Microsoft Sustainability Fund, Interface, MKA Foundation, and others.
#  Find out more at www.BuildingTransparency.org
#

# THE CONTENT OF THIS FILE IS AUTO-GENERATED BY OPENEPD SDK
# DO NOT EDIT MANUALLY
from openepd.model.specs.aluminium import AluminiumExtrusionsV1, AluminiumV1
from openepd.model.specs.asphalt import AsphaltV1
from openepd.model.specs.base import SpecsFactory

__all__ = ["spec_factory"]

from openepd.model.specs.concrete import ConcreteV1, FlowableFillV1, ReadyMixV1

spec_factory = SpecsFactory()
# GENERATED CODE STARTS HERE
spec_factory.register_spec("Aluminium", AluminiumV1)
spec_factory.register_spec("Aluminium.AluminiumExtrusions", AluminiumExtrusionsV1)
spec_factory.register_spec("Asphalt", AsphaltV1)
spec_factory.register_spec("Concrete", ConcreteV1)
spec_factory.register_spec("Concrete.ReadyMix", ReadyMixV1)
spec_factory.register_spec("Concrete.FlowableFill", FlowableFillV1)
# GENERATED CODE ENDS HERE
spec_factory.init()
