from typing import Any

from openepd.model.common import Amount


# Do not edit this file.
# It is generated with tools/openepd/codegen/generate_category_tree.py, or `make codegen-category-tree`

def get_category_definitions() -> tuple[dict[str, Any], ...]:
    """
    Return the tuple of category definitions used to build the category tree.

    :return: Tuple of dictionaries, each representing a category definition.
    """

    # The returned value is not a constant and is intended for temporary use only.
    # For persistent access to the category tree, use the immutable CATEGORY_TREE mapping instead.
    return (
        {%- for category in categories %}
        {
            "unique_name": "{{ category["unique_name"] }}",
            "display_name": "{{ category["display_name"] }}",
            "hierarchical_name": "{{ category["hierarchical_name"] }}",
            {%- if category["short_name"] %}
            "short_name": "{{ category["short_name"] }}",
            {%- endif %}
            {%- if category["historical_names"] %}
            "historical_names": {{ category["historical_names"] }},
            {%- endif %}
            {%- if category["alt_names"] %}
            "alt_names": {{ category["alt_names"] }},
            {%- endif %}
            {%- if category["description"] %}
            "description": "{{ category["description"] }}",
            {%- endif %}
            {%- if category["masterformat"] %}
            "masterformat": "{{ category["masterformat"] }}",
            {%- endif %}
            {%- if category["declared_unit"] %}
            "declared_unit": Amount(qty={{ category["declared_unit"].qty }}, unit="{{ category["declared_unit"].unit }}"),
            {%- endif %}
            "parent": {% if category["parent"] %}"{{ category["parent"] }}"{% else %}None{% endif %},
        },
        {%- endfor %}
    )
