from enum import StrEnum

# Do not edit this file. It is generated with tools/openepd/codegen/generate_geography_enum.py, or `make codegen`

class Geography(StrEnum):
    """
    Geography definitions.

    Special geography regions:
    {% for code, description in special_regions.items() %}
     * {{code}}: {{description}}{% endfor %}

    Country geography regions, see https://en.wikipedia.org/wiki/ISO_3166-1
    {% for code, description in countries.items() %}
     * {{code}}: {{description}}{% endfor %}

    USA states and Canada provinces, see https://en.wikipedia.org/wiki/ISO_3166-1:
    {% for code, description in us_canada_subdivisions.items() %}
     * {{code}}: {{description}}{% endfor %}

    UN m49 codes for countries and regions (i.e. both Egypt and Northern Africa)
    See https://unstats.un.org/unsd/methodology/m49/overview/
    {% for code, description in m49_codes.items() %}
     * m49_{{code}}: {{description}}{% endfor %}

    """

    # Special geography{% for code, description in special_regions.items() %}
    {{code}}= "{{code}}"{% endfor %}

    # Countries{% for code, description in countries.items() %}
    {{code | to_python_name}}= "{{code}}"{% endfor %}

    # USA and Canada subdivisions{% for code, description in us_canada_subdivisions.items() %}
    {{code | to_python_name}}= "{{code}}"{% endfor %}

    # m49 codification{% for code, description in m49_codes.items() %}
    m49_{{code | to_python_name}}= "{{code}}" # {{description}}{% endfor %}

class Country(StrEnum):
    """
    Geography definitions.

    Countries, see https://en.wikipedia.org/wiki/ISO_3166-1
    {% for code, description in countries.items() %}
     * {{code}}: {{description}}{% endfor %}
    """

    # Countries{% for code, description in countries.items() %}
    {{code | to_python_name}}= "{{code}}"{% endfor %}
