name: Build wheel
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
    secrets:
      pypi_token:
        required: true

jobs:
  run:
    name: Build and Publish python packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: "${{ ((inputs.git_ref) && inputs.git_ref) || github.ref }}"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          make verify-prerequisites deps NO_VENV=1

      - name: Build and publish packages
        run: |
          poetry config pypi-token.pypi "${{ secrets.pypi_token }}"
          make publish NO_VENV=True

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*
