name: Release
on:
  workflow_dispatch:
jobs:
  sanity-check:
    name: Run sanity check
    uses: ./.github/workflows/sanity-check.yml
    with:
      git_ref: '${{ github.ref }}'

  prepare-release:
    name: Prepare Release
    needs: [ sanity-check ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.bump.outputs.new_version }}
      release_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel commitizen~=2.42.1

      - name: Create Bump Commit
        id: bump
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # Dry run to generate change incremental change
          mkdir -p meta
          cz bump --yes --dry-run --changelog > bump.txt
          cat bump.txt | tail -n +5 > meta/new-changelog.md
          cat bump.txt
          echo "=============================="
          # Change log
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "changelog<<$EOF" >> "$GITHUB_OUTPUT"
          cat meta/new-changelog.md >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
          rm -rf meta
          # Actual bump
          make release NO_VENV=1
          echo "new_version=$(cz version --project)" >> "$GITHUB_OUTPUT"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Merge current branch -> prod
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: '${{ github.ref }}'
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Github Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ steps.bump.outputs.new_version }}'
          name: 'Version ${{ steps.bump.outputs.new_version }}'
          body: |
            ${{ steps.bump.outputs.changelog }}
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-wheel:
    name: Release python package
    needs: [ prepare-release ]
    uses: ./.github/workflows/build-and-publish-wheel.yml
    with:
      git_ref: 'refs/tags/${{ needs.prepare-release.outputs.version }}'
    secrets:
      pypi_token: '${{ secrets.pypi_token }}'

  attach-assets:
    name: Attach release assets
    needs: [ prepare-release, build-wheel ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
