name: Sanity Check
on:
  push:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
jobs:
  run:
    name: Sanity check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: "${{ ((inputs.git_ref) && inputs.git_ref) || github.ref }}"

      - name: Set up Python and Poetry
        uses: cchangelabs/action-setup-python-poetry@v1
        with:
          python-version: 3.11
          poetry-version: 2.1.3

      - name: Install dependencies
        run: |
          make setup

      - name: Lint
        run: make lint

      - name: Run build to make sure it works
        run: make build
